version: 0.1

phases:
  build:
    commands:
      - echo Nothing to do yet

artifacts:
  files:
    - index.html
    - blog.html
    - favicon.ico
    - AdithyaNeelavara-Resume.pdf
    - images/*
    - styles/*
    - js/*